### ISSUE TITLE
Cannot build on Windows

### ISSUE THREAD

**Issue by dennisbrouwer91** [NatelEnergy/grafana-discrete-panel#101]
Hi,

Trying to build this on Windows but i get : 

> yarn run v1.22.0
> $ grafana-toolkit plugin:build
> - Cleaning  (node:16952) ExperimentalWarning: The fs.promises API is experimental
> √ Cleaning
> √ Preparing
> - Prettier check  Trace: TypeError: results.flat is not a function
>       at C:\Users\Dennis\Documents\test\grafana-discrete-panel\node_modules\@grafana\toolkit\src\cli\tasks\plugin.build.js:76:124
>       at process._tickCallback (internal/process/next_tick.js:68:7)
>       at C:\Users\Dennis\Documents\test\grafana-discrete-panel\node_modules\@grafana\toolkit\src\cli\utils\useSpinner.js:24:29
>       at step (C:\Users\Dennis\Documents\test\grafana-discrete-panel\node_modules\tslib\tslib.js:136:27)
>       at Object.throw (C:\Users\Dennis\Documents\test\grafana-discrete-panel\node_modules\tslib\tslib.js:117:57)
>       at rejected (C:\Users\Dennis\Documents\test\grafana-discrete-panel\node_modules\tslib\tslib.js:108:69)
>       at process._tickCallback (internal/process/next_tick.js:68:7)
> × results.flat is not a function
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Any idea?

**Comment by edum18** [comment]
same here
