### ISSUE TITLE
Bug after Version 4.6.3 December 14, 2017

### ISSUE THREAD

**Issue by fherrador** [NatelEnergy/grafana-discrete-panel#38]
Looks that a new internal change has broken the plugin again:

Message:
Cannot read property 'from' of undefined
Stack trace:
TypeError: Cannot read property 'from' of undefined
    at t.getTimeFilter (http://178.32.76.254:3001/public/build/0.be20b78823b4c9d93a84.js:7:113735)
    at t.query (http://178.32.76.254:3001/public/build/0.be20b78823b4c9d93a84.js:7:110134)
    at DiscretePanelCtrl.issueQueries (http://178.32.76.254:3001/public/plugins/natel-discrete-panel/module.js:442:31)
    at u (http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:68722)
    at http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:69127
    at f.$digest (http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:74824)
    at f.$apply (http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:76638)
    at http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:72697
    at i (http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:21870)
    at http://178.32.76.254:3001/public/build/vendor.2305a8e1d478628b1297.js:43:23332

**Comment by ryantxu** [comment]
I assume this is fixed... @fherrador  can you open a new issue if it is not?
